export default interface ILanguageModel
{
    askLogin: string,
    askPassword: string,
    commentMechanic: string;
    infoIncorrectData: string,
    outEnterQuestion: string,
    askEmail: string,
    askPhone: string,
    askFio: string, 
    askPass: string,
    outRegQuestion: string,
    noEmptyField: string,
    yes: string,
    important: string,
    questionYear: string
    questionMonth: string
    questionDay: string,
    serviceName: string,
    errorGetScheduleInfo: string,
    errorGetMechanicInfo: string,
    errorGetCarInfo: string;
    errorGetApplications: string;
    errorCreateApplication: string;
    updateApplicationAdminMenu: string;
    updateApplicationAdminMechanic: string;
    serviceDiscription: string,
    servicePrice: string,
    carListEmpty: string
    carMark: string,
    carRun: string,
    carColor: string,
    carVIN: string,
    carYear: string,
    carNick: string,
    carOwner: string,
    carOwnerID: string,
    askCarMark: string,
    askCarRun: string,
    askCarColor: string,
    askCarVIN: string,
    askCarYear: string,
    askCarNick: string
    userFIO: string,
    userEmail: string,
    userType: string,
    userPhone: string,
    userDatebirth: string,
    userRoleClient: string,
    userRoleAdmin: string,
    userRoleMechanic: string,
    userRolePassword: string,
    userPasswordCapcha: string,
    carAdd: string;
    carUpdate: string;
    askInputNumber: string;
    outAddCarQuestion: string;
    tokenExpired: string;
    inputIncorrect: string;
    inputCarNUmber: string;
    outUpdateCarQuestion: string;
    status: string;
    date: string;
    createdStatus: string;
    savedClient: string;
    dirty: string;
    closed: string;
    noApplicationRecord: string;
    inputDateBirth: string;
    inputServiceNumber: string;
    outCreateApplication: string;
    outUpdateApplication: string,
    askChangeStatus: string;
    warningIgnore: string;
    adminClientMenu: string;
    adminMechanicMenu: string;
    incorrectInput: string;
    userColumnEmail: string;
    userColumnName: string;
    userColumnPhone: string;
    userColumnAskAction: string;
    clientLastInTable: string;
    mehcanicLastInTable: string;
    userGetInfoZero: string
    userGetInfoMoreTahnOne: string;
    seachEmailClient: string;
    errorIncorrectEmail: string;
    errorIncorrectPhone: string;
    userCarList: string;
    clientMenuForAdmin: string;
    mechanicMenuForAdmin: string;
    carExit: string;
    no: string;
    askMechanicStatus: string;
    askCarNickEmpty: string;
    userStatusField: string;
    userStatusStored: string;
    userStatusArchived: string;
    userStatusVocation: string;
    userInVocationImpossibleChange: string;
    inputStartDatePeriod: string;
    inputEndDatePeriod: string;
    errorStartEnd: string;
    service: string;
    errorApplicationIncorrect: string;
    askIfUserNeedDataInfo: string;
    applicationsMenuForAdmin: string;
    applicationMenuForAdmin: string;
    askInputApplicationNumber: string;
    duration: string;
    noDateInfo: string;
    errorGetClientName: string;
    box: string;
    errorGetServiceName: string;
    errorGetMechanicAndSheduleInfo: string;
    statusMenu: string;
    errorImpossibleChangeApplicationStatus: string;
    errorImpossibleUpdateApplication: string;
    wouldUpdateMechanic: string;
    errorImpossibleUpdateMechanic: string;
    dayWeek: string;
    timeStart: string;
    timeEnd: string;
    archived: string;
    savedMechanicSchedule: string;
    askInputComment: string;
    dateStart: string;
    dateEnd : string;
    vocationMenuForAdmin: string;
    errorImpossibleCreateSameVocationPeriod: string;
    vocationDeleteAsk: string;
    errorDeleteVocation: string;
    mechanicApplicationMenu: string;
    impossibleUpdateComment: string;
    impossibleWorkWithApplication: string;
}